# Generated by Django 6.0.3 on 2026-04-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('transporte', 'Transporte 🚗'), ('comida', 'Comida 🍕'), ('hospedaje', 'Hospedaje 🏨'), ('entretenimiento', 'Entretenimiento 🎟️'), ('otros', 'Otros 📦')], default='otros', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_viajes.participante')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='gestion_viajes.viaje')),
            ],
        ),
    ]
