# Generated by Django 6.0.3 on 2026-05-11 20:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viajes', '0002_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='imagen_fondo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
