# Generated by Django 6.0.3 on 2026-05-19 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viajes', '0003_viaje_imagen_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
