# Generated by Django 6.0.3 on 2026-05-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('datos', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('destino', 'categoria')},
            },
        ),
    ]
