# Generated by Django 6.0.3 on 2026-05-03 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_viajes', '0002_gasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IDA', 'Ida'), ('REGRESO', 'Regreso')], default='IDA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de comprobante'), ('CONFIRMADO', 'Reserva confirmada')], default='PENDIENTE', max_length=15)),
                ('aerolinea', models.CharField(max_length=100)),
                ('numero_vuelo', models.CharField(max_length=20)),
                ('origen_codigo', models.CharField(help_text='Código IATA del aeropuerto de origen', max_length=5)),
                ('destino_codigo', models.CharField(help_text='Código IATA del aeropuerto de destino', max_length=5)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('duracion', models.CharField(blank=True, default='', max_length=20)),
                ('escalas', models.IntegerField(default=0)),
                ('escalas_texto', models.CharField(blank=True, default='Directo', max_length=50)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=5)),
                ('pasajeros', models.IntegerField(default=1)),
                ('offer_id', models.CharField(blank=True, default='', help_text='ID de la oferta en Duffel', max_length=255)),
                ('numero_asiento', models.CharField(blank=True, default='', max_length=10)),
                ('enlace_ticket', models.URLField(blank=True, default='')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_transporte/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró el trayecto', on_delete=django.db.models.deletion.CASCADE, related_name='trayectos_registrados', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(help_text='Viaje al que pertenece este trayecto', on_delete=django.db.models.deletion.CASCADE, related_name='trayectos', to='gestion_viajes.viaje')),
            ],
            options={
                'verbose_name': 'Trayecto',
                'verbose_name_plural': 'Trayectos',
                'ordering': ['fecha_salida'],
            },
        ),
    ]
