# Generated by Django 6.0.3 on 2026-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayecto',
            name='destino_codigo',
            field=models.CharField(help_text='Código IATA del aeropuerto de destino', max_length=50),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='origen_codigo',
            field=models.CharField(help_text='Código IATA del aeropuerto de origen', max_length=50),
        ),
    ]
