# Generated by Django 6.0.3 on 2026-05-04 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viajes', '0002_gasto'),
        ('transporte', '0002_alter_trayecto_destino_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrayectoAutobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IDA', 'Ida'), ('REGRESO', 'Regreso')], default='IDA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de comprobante'), ('CONFIRMADO', 'Reserva confirmada')], default='PENDIENTE', max_length=15)),
                ('linea_autobus', models.CharField(help_text='Ej: ETN, Primera Plus', max_length=100)),
                ('servicio', models.CharField(help_text='Ej: Lujo, Ejecutivo, Primera', max_length=100)),
                ('origen_nombre', models.CharField(help_text='Nombre de la ciudad o terminal de origen', max_length=100)),
                ('destino_nombre', models.CharField(help_text='Nombre de la ciudad o terminal de destino', max_length=100)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('duracion', models.CharField(blank=True, default='', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='MXN', max_length=5)),
                ('pasajeros', models.IntegerField(default=1)),
                ('cbus_id', models.CharField(blank=True, default='', help_text='ID de la reserva o clave única de CBus', max_length=255)),
                ('asientos', models.CharField(blank=True, default='', help_text='Números de asientos (ej: 12, 13)', max_length=50)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_autobus/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró el trayecto de autobús', on_delete=django.db.models.deletion.CASCADE, related_name='autobuses_registrados', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(help_text='Viaje al que pertenece este trayecto de autobús', on_delete=django.db.models.deletion.CASCADE, related_name='trayectos_autobus', to='gestion_viajes.viaje')),
            ],
            options={
                'verbose_name': 'Trayecto de Autobús',
                'verbose_name_plural': 'Trayectos de Autobús',
                'ordering': ['fecha_salida'],
            },
        ),
    ]
