# Generated by Django 6.0.3 on 2026-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_trayectoautobus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayecto',
            name='tipo',
            field=models.CharField(choices=[('IDA', 'Ida'), ('REGRESO', 'Regreso'), ('IDA_VUELTA', 'Ida y Vuelta')], default='IDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='trayectoautobus',
            name='tipo',
            field=models.CharField(choices=[('IDA', 'Ida'), ('REGRESO', 'Regreso'), ('IDA_VUELTA', 'Ida y Vuelta')], default='IDA', max_length=10),
        ),
    ]
