# Generated by Django 6.0.3 on 2026-03-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('COP', 'Peso Colombiano')], default='MXN', max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
