# Generated by Django 6.0.3 on 2026-05-01 18:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_viajes', '0002_gasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_id', models.IntegerField(db_index=True)),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('modificado', 'Modificado'), ('eliminado', 'Eliminado'), ('restaurado', 'Restaurado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle_antes', models.JSONField(blank=True, null=True)),
                ('detalle_despues', models.JSONField(blank=True, null=True)),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_gasto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de gasto',
                'verbose_name_plural': 'Auditoría de gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('categoria', models.CharField(choices=[('transporte', 'Transporte 🚗'), ('alojamiento', 'Alojamiento 🏨'), ('alimentacion', 'Alimentación 🍕'), ('entretenimiento', 'Entretenimiento 🎟️'), ('compras', 'Compras 🛍️'), ('gasolina_casetas', 'Gasolina / Casetas ⛽')], max_length=20)),
                ('fecha', models.DateField()),
                ('metodo_division', models.CharField(choices=[('equitativo', 'Equitativo'), ('porcentaje', 'Por porcentaje'), ('monto_fijo', 'Monto fijo')], default='equitativo', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_pagados', to='gestion_viajes.participante')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_compartidos', to='gestion_viajes.viaje')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GastoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('monto_pagado', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_deuda', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Solo aplica si método es por_porcentaje', max_digits=5, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='control_gastos.gasto')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_gastos', to='gestion_viajes.participante')),
            ],
            options={
                'verbose_name': 'Participación en gasto',
                'verbose_name_plural': 'Participaciones en gastos',
                'unique_together': {('gasto', 'participante')},
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('acreedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acreencias', to='gestion_viajes.participante')),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='gestion_viajes.participante')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='gestion_viajes.viaje')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'unique_together': {('viaje', 'deudor', 'acreedor')},
            },
        ),
        migrations.CreateModel(
            name='PresupuestoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_personal', to='gestion_viajes.participante')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_personales', to='gestion_viajes.viaje')),
            ],
            options={
                'verbose_name': 'Presupuesto personal',
                'verbose_name_plural': 'Presupuestos personales',
                'unique_together': {('viaje', 'participante')},
            },
        ),
    ]
