# Generated by Django 6.0.3 on 2026-05-05 21:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacion',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
