# Generated by Django 6.0.3 on 2026-05-12 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_gastos', '0002_alter_liquidacion_options_and_more'),
        ('gestion_viajes', '0002_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoparticipante',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participaciones_gastos', to='gestion_viajes.participante'),
        ),
    ]
