# Generated by Django 6.0.3 on 2026-04-21 03:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_viajes', '0002_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(help_text='Archivo de imagen (JPEG, PNG o HEIC).', max_length=255, verbose_name='image')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se subió la imagen al sistema.')),
                ('fecha_tomada', models.DateField(blank=True, help_text='Fecha en que se tomó la fotografía (para agrupar en la galería).', null=True)),
                ('descripcion', models.CharField(blank=True, help_text='Pie de foto opcional.', max_length=255)),
                ('subida_por', models.ForeignKey(help_text='Participante del viaje que subió la imagen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_subidas', to='gestion_viajes.participante')),
                ('viaje', models.ForeignKey(help_text='Viaje al que pertenece esta imagen.', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_galeria', to='gestion_viajes.viaje')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['-fecha_tomada', '-fecha_subida'],
            },
        ),
    ]
