# Generated by Django 6.0.3 on 2026-04-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viaje_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('archivo', models.ImageField(upload_to='galeria/%Y/%m/%d/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('hora_subida', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de galería',
                'verbose_name_plural': 'Fotos de galería',
                'db_table': 'foto_galeria',
                'ordering': ['-fecha_subida', '-hora_subida'],
            },
        ),
    ]
