# Generated by Django 6.0.3 on 2026-04-20 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='responsable',
            new_name='creador',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='nombre',
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('VOTACION', 'En Votación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='VOTACION', max_length=15),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='hora',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='Actividad sin título', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='VotoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('SI', 'A Favor'), ('NO', 'En Contra')], max_length=2)),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='actividades.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('actividad', 'usuario')},
            },
        ),
    ]
