# Generated by Django 6.0.3 on 2026-05-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatabandonado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='fijado',
            field=models.BooleanField(default=False),
        ),
    ]
